Add update file, refactor

diff --git a/sebpi b/sebpi
--- a/sebpi
+++ b/sebpi
@@ -2,11 +2,17 @@
 
 COMMAND=$1
 SEBPI_SETUP_FILE_NAME="sebpi-setup.sh"
+SEBPI_UPDATE_FILE_NAME="sebpi-update.sh"
 RASPI_IP_ADDRESS="192.168.1.2"
 
 function usage() {
     echo "Usage: $0 <install|setup>"
     return -1
+}
+
+function fail() {
+    echo "$0 error: $1"
+    exit -1
 }
 
 function confirm() {
@@ -24,8 +30,8 @@ function confirm() {
 
 function install() {
     if [[ "$#" -ne 2 ]]; then
-        echo "Usage: sebpi install <img_file> <dev_disk>"
-        echo "Example: sebpi install raspbian-stretch-lite.img /dev/rdisk3"
+        echo "Usage: $0 install <img_file> <dev_disk>"
+        echo "Example: $0 install raspbian-stretch-lite.img /dev/rdisk3"
         return -1
     fi
 
@@ -34,20 +40,21 @@ function install() {
 
     confirm "WARNING: This will erase completely the contents of the SD card at $DEV_DISK. Do you want to proceed? [y/N]" || return -1
 
-    sudo diskutil eraseDisk FAT32 RASPBIAN MBRFormat ${DEV_DISK/r/} || return -1
+    sudo diskutil eraseDisk FAT32 RASPBIAN MBRFormat ${DEV_DISK/r/} || fail "Could not erase ${DEV_DISK/r/}"
     sleep 5
-    diskutil unmountdisk ${DEV_DISK/r/} || return -1
+    diskutil unmountdisk ${DEV_DISK/r/} || fail "Could not unmount ${DEV_DISK/r/}"
     sleep 5
-    sudo dd if="$IMG_FILE" of=$DEV_DISK bs=1m || return -1
+    sudo dd if="$IMG_FILE" of=$DEV_DISK bs=1m || fail "Could not copy $IMG_FILE onto $DEV_DISK"
     sleep 5
-    touch /Volumes/boot/ssh
+    sudo touch /Volumes/boot/ssh || fail "Could not touch file /boot/ssh"
     cp "$SEBPI_SETUP_FILE_NAME" /Volumes/boot
-    diskutil unmountdisk ${DEV_DISK/r/} || return -1
+    cp "$SEBPI_UPDATE_FILE_NAME" /Volumes/boot
+    diskutil unmountdisk ${DEV_DISK/r/} || fail "Could not unmount ${DEV_DISK/r/}"
     sed -i '' "/^$RASPI_IP_ADDRESS /d" ~/.ssh/known_hosts
 
     echo "Done! To continue:"
     echo "  1. Insert your microSD card in the Raspberry Pi and turn it on."
-    echo "  2. Wait 5 minutes"
+    echo "  2. Wait 5 minutes (seriously)."
     echo "  3. Come back to this terminal here and run 'sebpi setup'"
 
     return 0
@@ -57,6 +64,8 @@ function setup() {
     # run /boot/sebpi-install.sh on ssh
     ##
     sed -i '' "/^$RASPI_IP_ADDRESS /d" ~/.ssh/known_hosts
+    echo "Running sebpi-update.sh on the Raspberry Pi..."
+    ssh -t pi@$RASPI_IP_ADDRESS "sudo /boot/$SEBPI_UPDATE_FILE_NAME"
     echo "Running sebpi-install.sh on the Raspberry Pi..."
     ssh -t pi@$RASPI_IP_ADDRESS "sudo /boot/$SEBPI_SETUP_FILE_NAME"
     echo "Please change the password (default: raspberry)"
